packages:
  unix:
    common:
      - bat
      - btop
      - fzf
      - git
      - git-delta
      - neovim
      - tar
      - tmux
      - zsh
    gui:
      - kitty

tools:
  shell: zsh
  editor: nvim
  node: '24.13.0'

pathEntries:
  - '$HOME/.local/bin'
  - '$HOME/.bin'
  - '$HOME/.nodejs/bin'
  - '$HOME/.bun/bin'
  - '$HOME/.cache/.bun/bin'
