packages:
  unix:
    common:
      - bat
      - btop
      - fzf
      - gcc
      - git
      - git-delta
      - lazygit
      - neovim
      - ripgrep
      - tar
      - tmux
      - tree
      - zsh
    gui:
      - kitty
  npm:
    - opencode-ai
    - tree-sitter-cli

tools:
  shell: zsh
  editor: nvim

wsl:
  config:
    boot:
      systemd: true
    interop:
      appendWindowsPath: false
  # Reference at https://man7.org/linux/man-pages/man5/fstab.5.html
  fstab:
    - spec: 'tmpfs'
      file: '/tmp'
      vfstype: tmpfs
      mntops: ['defaults','nodev','nosuid','noatime','size=256m']
      freq: 0
      passno: 0

pathEntries:
  - '$HOME/.local/bin'
  - '$HOME/.bun/bin'
  - '$HOME/.cache/.bun/bin'
