packages:
  unix:
    common:
      - bat
      - btop
      - curl
      - fzf
      - gcc
      - git
      - git-delta
      - lazygit
      - neovim
      - ripgrep
      - tar
      - tmux
      - tree
      - zsh
    gui:
      - kitty
  windows:
    - AntibodySoftware.WizTree
    - Brave.Brave
    - Discord.Discord
    - KDE.KDEConnect
    - KDE.Okular
    - MartiCliment.UniGetUI
    - Microsoft.PowerShell
    - Microsoft.PowerToys
    - Microsoft.VisualStudioCode
    - Microsoft.WindowsTerminal
    - ONLYOFFICE.DesktopEditors
    - Obsidian.Obsidian
    - REALiX.HWiNFO
    - Rclone.Rclone
    - RevoUninstaller.RevoUninstaller
    - VideoLAN.VLC
    - WinFsp.WinFsp
    - WinSCP.WinSCP
    - CrystalDewWorld.CrystalDiskInfo
    - jtroo.kanata_gui
    - nomacs.nomacs
    - '9NKSQGP7F2NH'  # WhatsApp
  npm:
    - opencode-ai
    - tree-sitter-cli

tools:
  shell: zsh
  editor: nvim

treesitter:
  'tree-sitter-grammars/tree-sitter-markdown':  # Repo slug
    build:
      tree-sitter-markdown: markdown  # Folder -> parser name mapping
      tree-sitter-markdown-inline: markdown_inline
  'tree-sitter/tree-sitter-typescript':
    build:
      tsx: tsx
      typescript: typescript
  'tree-sitter/tree-sitter-bash':
    build:
      .: bash
  'ngalaiko/tree-sitter-go-template':
    build:
      .: gotmpl
  'tree-sitter/tree-sitter-javascript':
    build:
      .: javascript
  'tree-sitter/tree-sitter-python':
    branch: 'v0.23.6'
    build:
      .: python
  'tree-sitter-grammars/tree-sitter-yaml':
    build:
      .: yaml
  'tree-sitter-grammars/tree-sitter-lua':
    build:
      .: lua

wsl:
  config:
    boot:
      systemd: true
    interop:
      appendWindowsPath: false
  # Reference at https://man7.org/linux/man-pages/man5/fstab.5.html
  fstab:
    - spec: 'tmpfs'
      file: '/tmp'
      vfstype: tmpfs
      mntops: ['defaults','nodev','nosuid','noatime','size=256m']
      freq: 0
      passno: 0

pathEntries:
  - '$HOME/.local/bin'
  - '$HOME/.bun/bin'
  - '$HOME/.cache/.bun/bin'
